swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http

tags:
  - name: Transactions
    description: Operations to manage transactions
  - name: User
    description: Operations to manage users

paths:
  /user/login:
    post:
      tags:
        - User
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: 'string'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: 'string'
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions
      description: Get all transactions of the current month
      produces:
        - application/json
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token.
          type: string
          required: true
        - in: query
          name: filter_date
          description: allow date filter
          type: string
          format: date
          required: true
      responses:
        200:
          description: Get Transactions Successfully
          schema:
            type: "array"
            items: 
              $ref: '#/definitions/Transaction'
        400:
          description: Invalid Fields Supplied
        401:
          description: Unauthorized Access To Get Transactions 
        404:
          description: Transactions Not Found
        500:
          description: Internal Server Error
  /transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions
      description: Get a transaction by id
      produces:
        - application/json
      parameters:
        - in: path
          name: transactionId
          description: ID to select a specific transaction
          required: true
          type: integer
        - in: header
          name: Authorization
          description: Attach Bearer JWT token.
          type: string
          required: true
      responses:
        200:
          description: Get Transaction Successfully
          schema:
            $ref: '#/definitions/Transaction'
        400:
          description: Invalid Fields Supplied
        401:
          description: Unauthorized Access
        404:
          description: Transaction Not Found
        500:
          description: Internal Server Error
    post:
      security:
        - Bearer: []
      tags:
        - Transactions
      description: Add new transaction's informations
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: transactionId
          description: ID to select a specific transaction
          required: true
          type: integer
        - in: header
          name: Authorization
          description: Attach Bearer JWT token.
          type: string
          required: true
        - in: body
          name: body
          description: Transaction Payload
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      responses:
        201:
          description: Transaction's informations Added Successfully
          schema:
            $ref: '#/definitions/Transaction'
        400:
          description: Invalid Transaction Payload Supplied
        401:
          description: Unauthorized Access
        500:
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Transactions
      description: Total update of transaction's informations
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: transactionId
          description: ID to select a specific transaction
          required: true
          type: integer
        - in: header
          name: Authorization
          description: Attach Bearer JWT token.
          type: string
          required: true
        - in: body
          name: body
          description: Total update of transaction's informations
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      responses:
        204:
          description: Successful Update Operation
        400:
          description: Invalid Fields Supplied
        401:
          description: Unauthorized Access
        404:
          description: Transaction Not Found
        500:
          description: Internal Server Error
    patch:
      security:
        - Bearer: []
      tags:
        - Transactions
      description: Partial update of transaction's informations
      consumes:
        - application/merge-patch+json
      produces:
        - application/merge-patch+json
      parameters:
        - in: path
          name: transactionId
          description: ID to select a specific transaction
          required: true
          type: integer
        - in: header
          name: Authorization
          description: Attach Bearer JWT token.
          type: string
          required: true
        - in: body
          name: body
          description: Partial update of transaction's informations
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      responses:
        204:
          description: Successful Partial Update Operation
        400:
          description: Invalid Transaction Fields Supplied
        401:
          description: Unauthorized Access
        404:
          description: Transaction Not Found
        500:
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - Transactions
      description: Delete a transaction
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: transactionId
          description: ID to select a specific transaction
          type: integer
          required: true
        - in: header
          name: Authorization
          description: Attach Bearer JWT token.
          type: string
          required: true
      responses:
        200:
          description: Successful Deletion Operation
          schema: 
            $ref: '#/definitions/TransactionDeletedResponse'
        401:
          description: Unauthorized Access
        404:
          description: Transaction Not Found
        500:
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  Transaction:
    type: object
    properties:
      id:
        type: string
        description: transaction ID
      created:
        type: string
        description: transaction date
      description:
        type: string
        description: transaction description
      amount:
        type: number
        description: transaction amount
      balance:
        type: number
        description: account balance after transaction
      transactionType:
        type: string
        description: transaction type
      category:
        type: string
        description: transaction category
      note:
        type: string
        description: user's notes for transaction
  TransactionDeletedResponse:
      type: object
      properties:
        status:
          type: integer
          example: 200
        message:
          type: string
          example: Transaction deleted  